package dev.drzepka.typing.server.application.dto

/**
 * Holds multiple validation errors of type [ValidationErrorDTO].
 */
class ValidationErrorsDTO {
    val errors = ArrayList<ValidationErrorDTO>()
}

/**
 * Contains a single validation error.
 */
class ValidationErrorDTO {
    var type = ""
    var field: String? = null
    var message = ""
}

@Suppress("unused")
class UnknownFieldErrorDTO(field: String, knownFields: Collection<String>) {
    val message = "Unrecognized field '$field'. Known fields: ${knownFields.joinToString()}"
}

/**
 * Contains errors generated by the application.
 */
@Suppress("unused")
class ErrorCodeDTO(
    val code: String,
    val message: String,
    val `object`: Any? = null,
    val additionalData: Map<String, Any>? = null
)